# Generated by Django 5.2.8 on 2025-11-15 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('expert', 'Expert')], max_length=50)),
                ('requirements', models.TextField()),
                ('reward', models.CharField(blank=True, max_length=100)),
                ('icon', models.ImageField(upload_to='achievements/')),
            ],
        ),
        migrations.CreateModel(
            name='Arena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('arena_type', models.CharField(choices=[('standard', 'Standard'), ('competitive', 'Competitive'), ('special', 'Special Event')], max_length=50)),
                ('environment', models.CharField(max_length=100)),
                ('capacity', models.CharField(max_length=50)),
                ('special_features', models.TextField()),
                ('image', models.ImageField(upload_to='arenas/')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('rarity', models.CharField(choices=[('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare'), ('very_rare', 'Very Rare'), ('import', 'Import'), ('exotic', 'Exotic'), ('black_market', 'Black Market')], max_length=50)),
                ('hitbox', models.CharField(max_length=50)),
                ('release_date', models.DateField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='cars/')),
                ('price', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GameUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50)),
                ('release_date', models.DateField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('major_changes', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='updates/')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('season', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('prize_pool', models.CharField(max_length=100)),
                ('winner', models.CharField(max_length=100)),
                ('runner_up', models.CharField(max_length=100)),
                ('mvp', models.CharField(max_length=100)),
                ('highlights', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='tournaments/')),
            ],
        ),
        migrations.CreateModel(
            name='VisitorComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
