# Generated by Django 5.2.8 on 2025-11-16 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='achievements/'),
        ),
        migrations.AlterField(
            model_name='arena',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='arenas/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cars/'),
        ),
        migrations.AlterField(
            model_name='gameupdate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='updates/'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tournaments/'),
        ),
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('video_url', models.URLField(help_text='YouTube или Vimeo ссылка')),
                ('player', models.CharField(help_text='Игрок или команда', max_length=100)),
                ('moment_type', models.CharField(choices=[('aerial', 'Ариал'), ('double_tap', 'Двойное касание'), ('ceiling_shot', 'Удар с потолка'), ('musty_flick', 'Флик Масти'), ('bump_play', 'Столкновение'), ('save', 'Сейв'), ('pass_play', 'Командная игра'), ('zero_second', 'Гол на последней секунде'), ('other', 'Другое')], max_length=50)),
                ('duration', models.CharField(help_text='Например: 0:15', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights_videos', to='museum.tournament')),
            ],
        ),
    ]
