# Generated by Django 5.2.8 on 2025-11-16 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0002_alter_achievement_icon_alter_arena_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlight',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Превью для видео', null=True, upload_to='highlights/thumbnails/'),
        ),
        migrations.AddField(
            model_name='highlight',
            name='video_file',
            field=models.FileField(blank=True, help_text='Загрузите видео файл (MP4, WebM, MOV)', null=True, upload_to='highlights/videos/'),
        ),
        migrations.AlterField(
            model_name='highlight',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube или Vimeo ссылка'),
        ),
    ]
